import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import { Zap, Settings, Sparkles, Cpu, Shield, Brain, MessageSquare, Activity, ChevronRight } from "lucide-react";
import ForgeLayout from "@/components/forge/ForgeLayout";
import DataStream from "@/components/forge/DataStream";
import UpgradeBanner from "@/components/forge/UpgradeBanner";
import PaywallModal from "@/components/forge/PaywallModal";

const AGENT_ICONS = {
  "Orchestrator": { Icon: Zap, color: "#8B5CF6" },
  "Security Guardian": { Icon: Shield, color: "#EF4444" },
  "Recall Agent": { Icon: Brain, color: "#8B5CF6" },
  "Communication Agent": { Icon: MessageSquare, color: "#3B82F6" },
  "Resilience Agent": { Icon: Activity, color: "#10B981" },
};

export default function Brief() {
  const navigate = useNavigate();
  const [profile, setProfile] = useState(null);
  const [logs, setLogs] = useState([]);
  const [brief, setBrief] = useState(null);
  const [generatingBrief, setGeneratingBrief] = useState(false);
  const [showPaywall, setShowPaywall] = useState(false);
  const [now, setNow] = useState(new Date());

  useEffect(() => {
    loadData();
    const timer = setInterval(() => setNow(new Date()), 1000);
    return () => clearInterval(timer);
  }, []);

  const loadData = async () => {
    const [profiles, systemLogs, briefs] = await Promise.all([
      base44.entities.UserProfile.list(),
      base44.entities.SystemLog.list("-created_date", 20),
      base44.entities.DailyBrief.list(),
    ]);
    if (profiles.length > 0) setProfile(profiles[0]);
    setLogs(systemLogs);
    const today = new Date().toISOString().split("T")[0];
    const todayBrief = briefs.find(b => b.briefDate === today);
    if (todayBrief) setBrief(todayBrief);
  };

  const generateBrief = async () => {
    setGeneratingBrief(true);
    const [visions, secEvents] = await Promise.all([
      base44.entities.Vision.list(),
      base44.entities.SecurityEvent.list(),
    ]);
    const result = await base44.integrations.Core.InvokeLLM({
      prompt: `Generate a cinematic, motivational morning briefing for ${profile?.name || "Commander"} in ${profile?.location || "the field"}. 
They have ${visions.length} visions archived and ${secEvents.length} security events logged. 
Speak as the Crystal Core intelligence — year 2050, authoritative, mystical, concise. 
Cover: what's stirring today, what the agents noticed, what to focus on, and a powerful directive.
Keep it under 120 words. No filler. Pure signal.`,
    });
    const today = new Date().toISOString().split("T")[0];
    const saved = await base44.entities.DailyBrief.create({
      content: result,
      briefDate: today,
    });
    await base44.entities.SystemLog.create({
      action: "Daily brief generated by Crystal Core.",
      reason: "Morning orchestration triggered.",
      agentName: "Orchestrator",
      impact: "Today's intelligence directive is live.",
    });
    setBrief(saved);
    setGeneratingBrief(false);
    loadData();
  };

  const handlePaywallSuccess = () => {
    setShowPaywall(false);
    setProfile(p => p ? { ...p, isPremium: true } : p);
    loadData();
  };

  const formatTime = (date) => date.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
  const formatDate = (date) => date.toLocaleDateString([], { weekday: "long", month: "long", day: "numeric" });

  return (
    <ForgeLayout dataStream={<DataStream variant="rain" opacity={0.18} />}>
      <div className="px-4 pt-6 pb-4">
        {/* Header */}
        <div className="flex items-start justify-between mb-6">
          <div>
            <p className="text-xs tracking-[0.35em] text-violet-500 uppercase mb-1">ORCHESTRATOR</p>
            <h1 className="text-2xl font-black text-white tracking-tight">{formatTime(now)}</h1>
            <p className="text-xs text-gray-500 mt-0.5">{formatDate(now)}</p>
          </div>
          <button
            onClick={() => navigate("/settings")}
            className="w-9 h-9 rounded-xl bg-white/3 border border-white/5 flex items-center justify-center"
          >
            <Settings className="w-4 h-4 text-gray-400" />
          </button>
        </div>

        {/* Greeting */}
        {profile && (
          <p className="text-sm text-gray-400 mb-6">
            Welcome back, <span className="text-white font-semibold">{profile.name}</span>.
          </p>
        )}

        {/* Upgrade Banner */}
        {profile && !profile.isPremium && (
          <div className="mb-4">
            <UpgradeBanner onUpgrade={() => setShowPaywall(true)} />
          </div>
        )}

        {/* Daily Brief */}
        <div className="bg-gradient-to-br from-violet-900/20 to-black border border-violet-500/20 rounded-2xl p-5 mb-4">
          <div className="flex items-center gap-2 mb-3">
            <Sparkles className="w-4 h-4 text-violet-400" />
            <p className="text-xs tracking-[0.35em] text-violet-400 uppercase font-bold">TODAY'S BRIEFING</p>
          </div>
          {brief ? (
            <p className="text-sm text-gray-300 leading-relaxed">{brief.content}</p>
          ) : (
            <div className="flex flex-col gap-3">
              <p className="text-sm text-gray-600">No briefing generated yet.</p>
              <button
                onClick={generateBrief}
                disabled={generatingBrief}
                className="self-start px-4 py-2 rounded-xl bg-violet-600/20 border border-violet-500/30 text-xs text-violet-300 font-bold tracking-wider uppercase disabled:opacity-50 hover:bg-violet-600/30 transition-colors"
              >
                {generatingBrief ? "GENERATING..." : "GENERATE MORNING BRIEF"}
              </button>
            </div>
          )}
        </div>

        {/* Crystal Core Status */}
        <div className="bg-white/2 border border-white/5 rounded-2xl p-4 mb-4 flex items-center gap-3">
          <Cpu className="w-5 h-5 text-emerald-400 flex-shrink-0" />
          <div className="flex-1">
            <p className="text-xs tracking-wider text-gray-500 uppercase">Crystal Core</p>
            <p className="text-sm text-white font-bold mt-0.5">AWAKE</p>
          </div>
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 rounded-full bg-emerald-400 dot-pulse" />
            <span className="text-xs text-emerald-400 font-bold">LIVE</span>
          </div>
        </div>

        {/* System Alerts */}
        <div className="mb-4">
          <div className="flex items-center justify-between mb-3">
            <p className="text-xs tracking-[0.35em] text-gray-500 uppercase">System Alerts</p>
            <button
              onClick={() => navigate("/activity")}
              className="text-[10px] text-violet-400 tracking-wider flex items-center gap-1"
            >
              VIEW ALL <ChevronRight className="w-3 h-3" />
            </button>
          </div>

          {logs.length === 0 ? (
            <div className="bg-white/2 border border-white/5 rounded-2xl p-5 text-center">
              <p className="text-xs text-gray-600">No system activity yet.</p>
            </div>
          ) : (
            <div className="flex flex-col gap-2">
              {logs.slice(0, 5).map(log => {
                const agent = AGENT_ICONS[log.agentName] || AGENT_ICONS["Orchestrator"];
                const Icon = agent.Icon;
                return (
                  <div key={log.id} className="bg-white/2 border border-white/5 rounded-xl p-3 flex items-start gap-3">
                    <div
                      className="w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5"
                      style={{ backgroundColor: `${agent.color}18` }}
                    >
                      <Icon className="w-3.5 h-3.5" style={{ color: agent.color }} />
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="text-xs text-white leading-snug">{log.action}</p>
                      {log.impact && <p className="text-[10px] text-gray-600 mt-0.5">{log.impact}</p>}
                      <p className="text-[10px] text-gray-700 mt-1">
                        {new Date(log.created_date).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })} · {log.agentName}
                      </p>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>

      {showPaywall && (
        <PaywallModal
          onClose={() => setShowPaywall(false)}
          onSuccess={handlePaywallSuccess}
        />
      )}
    </ForgeLayout>
  );
}
